config/routes.rb
Rails.application.routes.draw do
  resources :xmls

end

app/models/dado.rb
class Dado < ActiveRecord::Base
  belongs_to :tracksegment
  has_attached_file :gpx
end

app/models/tracksegment.rb
class Tracksegment < ActiveRecord::Base
  belongs_to :xml
  has_many :dados, :dependent => :destroy
end

app/models/xml.rb
class Xml < ActiveRecord::Base
	has_many :tracksegments, :dependent => :destroy
	has_many :dados, :through => :tracksegments


	has_attached_file :gpx
  before_save :parse_file
  validates_attachment_file_name :gpx, matches: [/xml\Z/]



  def parse_file
    tempfile = gpx.queued_for_write[:original]
    doc = Nokogiri::XML(tempfile)
    parse_xml(doc)
  end

  def parse_xml(doc)
    doc.root.elements.each do |node|
      parse_tracks(node)
    end
  end

  def parse_tracks(node)
    if node.node_name.eql? 'capture'
      node.elements.each do |node|
        parse_track_segments(node)
      end
    end
  end

def parse_track_segments(node)
    if node.node_name.eql? 'bbmessenger'
      tmp_segment = Tracksegment.new
      node.elements.each do |node|
        parse_points(node,tmp_segment)
      end
      self.tracksegments << tmp_segment
    end
  end


  def parse_points(node,tmp_segment)
    if node.node_name.eql? 'message'
      tmp_point = Dado.new

      node.elements.each do |node|
      tmp_point.nome = node.text.to_s if node.name.eql? 'name'
      tmp_point.origem = node.text.to_s if node.name.eql? 'contacts'
      tmp_point.destino = node.text.to_s if node.name.eql? 'name'
      tmp_point.mensagem = node.text.to_s if node.name.eql? 'text'
      tmp_point.hora = node.text.to_s if node.name.eql? '--'
      
      end
      tmp_segment.dados << tmp_point
    end

end






end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/xmls_controller.rb
class XmlsController < ApplicationController
  before_action :set_xml, only: [:show, :edit, :update, :destroy]

  # GET /xmls
  # GET /xmls.json
  def index
    @xmls = Xml.all
  end

  # GET /xmls/1
  # GET /xmls/1.json
  def show
  end

  # GET /xmls/new
  def new
    @xml = Xml.new
  end

  # GET /xmls/1/edit
  def edit
  end

  # POST /xmls
  # POST /xmls.json
  def create
    @xml = Xml.new(xml_params)

    respond_to do |format|
      if @xml.save
        format.html { redirect_to @xml, notice: 'Xml was successfully created.' }
        format.json { render :show, status: :created, location: @xml }
      else
        format.html { render :new }
        format.json { render json: @xml.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xmls/1
  # PATCH/PUT /xmls/1.json
  def update
    respond_to do |format|
      if @xml.update(xml_params)
        format.html { redirect_to @xml, notice: 'Xml was successfully updated.' }
        format.json { render :show, status: :ok, location: @xml }
      else
        format.html { render :edit }
        format.json { render json: @xml.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xmls/1
  # DELETE /xmls/1.json
  def destroy
    @xml.destroy
    respond_to do |format|
      format.html { redirect_to xmls_url, notice: 'Xml was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xml
      @xml = Xml.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xml_params
      params.require(:xml).permit(:alvo, :nome, :operacao, :fase, :gpx)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/xmls_helper.rb
module XmlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>
    	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>

    

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

<div class="container">
	
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>
          

          <%= yield %>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    

</div>	
  </body>
</html>

app/views/xmls/_form.html.erb
<%= form_for(@xml) do |f| %>
  <% if @xml.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@xml.errors.count, "error") %> prohibited this xml from being saved:</h2>

      <ul>
      <% @xml.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alvo %><br>
    <%= f.text_field :alvo %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :operacao %><br>
    <%= f.text_field :operacao %>
  </div>
  <div class="field">
    <%= f.label :fase %><br>
    <%= f.number_field :fase %>
  </div>

  <div class="field">
    <%= f.label :gpx %> <br>
      <%= f.file_field :gpx %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xmls/edit.html.erb
<h1>Editing Xml</h1>

<%= render 'form' %>

<%= link_to 'Show', @xml %> |
<%= link_to 'Back', xmls_path %>

app/views/xmls/index.html.erb
<p id="notice"><%= notice %></p>


      <div class="row">
        
        <div class="container-fluid">
          <h1 class="page-header">Dashboard</h1>

          

        

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Pin</th>
                  <th>Alvo</th>
                  <th>Nome</th>
                  <th>Operação</th>
                  <th>Fase</th>
                  <th>Arquivo</th>
                </tr>
              </thead>
              <tbody>
              <% @xmls.each do |xml| %>

              <tr>
                  <td>234677ss</td>
                  <td><%= xml.alvo %></td>
                  <td><%= xml.nome %></td>
                  <td><%= xml.operacao %></td>
                  <td><%= xml.fase %></td>
                  <td><%= xml.gpx_file_name %></td>
                  <td><%= link_to 'Show', xml %></td>
        <td><%= link_to 'Edit', edit_xml_path(xml) %></td>
        <td><%= link_to 'Destroy', xml, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  
                </tr>
             </tbody>  
             <% end %> 
            </table>
          </div>
        </div>
      </div>


<%= link_to 'New Xml', new_xml_path %>

app/views/xmls/new.html.erb
<h1>New Xml</h1>

<%= render 'form' %>

<%= link_to 'Back', xmls_path %>

app/views/xmls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alvo:</strong>
  <%= @xml.alvo %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @xml.nome %>
</p>

<p>
  <strong>Operacao:</strong>
  <%= @xml.operacao %>
</p>

<p>
  <strong>Fase:</strong>
  <%= @xml.fase %>
</p>



<div> 

  


<div class="row " style="padding-top:40px;">
   

                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Enter Message" />
                    <span class="input-group-btn">
                        <button class="btn btn-info" type="button">SEND</button>
                    </span>
                </div>




    <br /><br />
    <div class="col-md-12">
        <div class="pane panel-info">
            <div class="panel-heading">
                CHAT 
            </div>
            <div class="panel-body">
<ul class="media-list">

                                    <% @xml.dados.each do |point| %>
                                    <li class="media">

                                        <div class="media-body">

                                            <div class="media">
                                                <a class="pull-left" href="#">
                                                   <%= image_tag("1.png",  :class => "media-object img-circle") %>
                                                </a>
                                                <div class="media-body" >
                                                    <h4><%= point.mensagem %><h4>
                                                    
                                                    <br />
                                                   <small class="text-muted"><%= point.destino %> | <%= point.origem %></small>
                                                    <hr />
                                                </div>
                                            </div>

                                        </div>
                                    </li>
                                    <% end %>
                                    <li class="media"></li>
                                </ul>
            </div>
            
        </div>
    </div>
    
</div>



<%= link_to 'Edit', edit_xml_path(@xml) , :class =>"btn btn-primary" %> 
<%= link_to 'Back', xmls_path %>,